name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} - ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'zillionare/marktwain'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Determine build command
        id: build-command
        run: |
          if [[ "${{ secrets.BUILD_COMMAND }}" == "build:h5-netlify" ]]; then
            echo "BUILD_COMMAND=build:h5-netlify" >> $GITHUB_ENV
          else
            echo "BUILD_COMMAND=build" >> $GITHUB_ENV
          fi

      - name: Run build
        run: pnpm web ${{ env.BUILD_COMMAND }}

      - name: Create SPA support files
        run: |
          # 创建 .nojekyll 文件以禁用 Jekyll 处理
          touch apps/web/dist/.nojekyll
          
          # 创建 404.html 文件用于 SPA 路由重定向
          cat > apps/web/dist/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Redirecting...</title>
              <script>
                // 获取当前路径，去掉可能的查询参数和哈希
                const path = window.location.pathname;
                const search = window.location.search;
                const hash = window.location.hash;
                
                // 如果路径不是以 /md/ 开头，重定向到 /md/
                if (!path.startsWith('/md/')) {
                  window.location.replace('/md/' + (search + hash));
                } else {
                  // 如果路径以 /md/ 开头，重定向到 index.html
                  window.location.replace('/md/index.html' + search + hash);
                }
              </script>
            </head>
            <body>
              <p>Redirecting...</p>
            </body>
          </html>
          EOF
          
          # 创建 _redirects 文件用于 GitHub Pages SPA 支持
          cat > apps/web/dist/_redirects << 'EOF'
          # GitHub Pages SPA redirects
          # 将所有请求重定向到 index.html，让 Vue Router 处理路由
          /*    /md/index.html   200
          EOF

      # CNAME 文件仅在使用自定义域名时需要
      # 使用默认的 GitHub Pages 域名时不需要生成 CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: apps/web/dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
